# Generated by Django 4.1.2 on 2022-11-20 11:54

import django.core.validators
from django.db import migrations, models
import e_fish_shop_app.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), e_fish_shop_app.core.validators.only_letter_numbers_and_underscore_validator]),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), e_fish_shop_app.core.validators.only_letter_numbers_and_underscore_validator]),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
