# Generated by Django 4.1.2 on 2022-11-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
